name: Build/release

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  buildWindows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '21.x'
    - run : npm install
    - name: build package
      run: npm run package
    - name : upload package
      uses: actions/upload-artifact@v2
      with:
        name: windows-package
        path: |
          release/*.exe
