name: Code Quality

on: 
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  quality:
    runs-on : ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Biome
          uses: biomejs/setup-biome@v1
          with:
            version: 1.2.2
        - name: Run Biome
          run : biome ci .